version: "3.9"
services:
 postgres:
    image: postgres:16.2-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
    volumes:
      - mlops:/var/lib/postgresql/data
volumes:
 mlops: