apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contacts-backend
  template:
    metadata:
      labels:
        app: contacts-backend
    spec:
      containers:
        - name: contacts-backend-container
          image: ghcr.io/athifirshad/contacts-backend:1.0
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 4000
          env:
            - name: DB_DSN
              value: "host=host.minikube.internal port=5432 user=root password=secret dbname=contacts"

---
apiVersion: v1
kind: Service
metadata:
  name: contacts-backend-service
spec:
  selector:
    app: contacts-backend
  ports:
    - protocol: TCP
      name: web-port
      port: 4000
      targetPort: 4000
  type: LoadBalancer
