apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
 name: api-rollout
spec:
 replicas: 3
 selector:
    matchLabels:
      app: api
 template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api-container
        image: ghcr.io/athifirshad/demo:1.1
        ports:
        - containerPort: 4000
 strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: "30s"}
      - setWeight: 50
      - pause: {duration: "30s"}
      - setWeight: 100
      canaryService: api-canary
      stableService: api-stable