// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import ()

type Contact struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	PhoneNumber string `json:"phone_number"`
}
